import = [
    "~/.config/alacritty/themes/themes/fbch.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

opacity = 0.7

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 17

[mouse]
hide_when_typing = true
